### ISSUE TITLE
ply>=3.8 in install_requires

### ISSUE THREAD

**Issue by bcail** [emory-libraries/eulxml#28]
I just tried upgrading to eulxml 1.0.1, and it upgraded eulxml, but left ply at the old version (3.4). When I tried to run our tests, I got a ply.yacc.YaccError. After upgrading ply to 3.8, our tests were fine. Looks like maybe install_requires should specify the version of ply the same way setup_requires does. (See note at https://pythonhosted.org/setuptools/setuptools.html under setup_requires.)

**Comment by rlskoeser** [comment]
@bcail thanks for reporting this.  I can make the change, but I'm not sure how to duplicate your problem so that I can confirm that actually fixes it.  Are you using pip to install eulxml, or something else?  Perhaps some install tools behave differently - pip seems to upgrade ply when I try to duplicate your error (I'm using pip 8.1.1).

It probably won't hurt to make the change, but I thought I'd check if you have an idea about replicating the problem first, in case this doesn't solve it.

**Comment by bcail** [comment]
Here are some steps to reproduce:
1. create & activate a virtualenv
2. pip install --upgrade pip
3. pip install ply==3.4
4. pip install eulxml
*ply is left at version 3.4

**Comment by rlskoeser** [comment]
Thanks, you're absolutely right.  I was making it harder than it needed to be (installing an older version of eulxml and then upgrading), although I'm not sure why that caused a problem.  And the fix is exactly what you suggested.

**Comment by bcail** [comment]
Great! Thanks for looking at that.

**Comment by rlskoeser** [comment]
Fixed in 1.1.1
